\set ON_ERROR_STOP on

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tp01_owner') THEN
    CREATE ROLE tp01_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tp01_runtime') THEN
    CREATE ROLE tp01_runtime LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
END
$$;

ALTER ROLE tp01_runtime PASSWORD :'runtime_password';

REVOKE ALL ON DATABASE tp01 FROM PUBLIC;
GRANT CONNECT ON DATABASE tp01 TO tp01_runtime;
